
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/database';

const SUPABASE_URL = "https://magaioqzbanpabahgkdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hZ2Fpb3F6YmFucGFiYWhna2RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDg2MzIsImV4cCI6MjA2MDQ4NDYzMn0.pk_g-8zuA07tQnxMQqV4gQqzj_nJRDKT93WoISFsAe8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
